Implemented show logging buffered
NCATComp410/comp410_fall_2020 pull request #51
Opened 2020-10-17 03:50 UTC by LondonWesley

platform win32 -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: C:\Users\wesley\Desktop\softeng\comp410_fall_2020
plugins: cov-2.10.1
collected 8 items

asa_parser\tests\test_parser.py ........                                                                         [100%]

----------- coverage: platform win32, python 3.8.5-final-0 -----------
Name                              Stmts   Miss  Cover
-----------------------------------------------------
asa_parser\__init__.py                2      0   100%
asa_parser\src\asa_parse.py          34      7    79%
asa_parser\src\shtech_parse.py       27      1    96%
asa_parser\tests\__init__.py          0      0   100%
asa_parser\tests\test_parser.py      29      1    97%
-----------------------------------------------------
TOTAL                                92      9    90%

================================================== 8 passed in 1.50s ==================================================

(py38) C:\Users\wesley\Desktop\softeng\comp410_fall_2020>

2020-10-17 12:01 UTC, claesmk commented on demo.py
> +    print(primary_asa.show_logging_buffered())
This doesn't currently return anything due to the error noted above.
```
{"text": []}
```
Once you've corrected that problem the output should look something like this:
```
{"text": ["Aug 16 2017 15:35:37 KP-systest-admin : %ASA-4-711004: Task ran for 114 msec, Process = Unicorn Admin Handler, PC = f34bf8f4, Call stack = ", "Aug 16 2017 15:36:12 KP-systest-admin : %ASA-4-711004: Task ran for 108 msec, Process ...
```

2020-10-17 12:03 UTC, claesmk requested changes

2020-10-17 12:03 UTC, claesmk commented on asa_parser/src/asa_parse.py
> +        return json.dumps({'text': self.get_show_section('show logging buffered')})
the get_show_section() function automatically handles the work "show" - actually it's designed to handle custom prefixes too
```
    def get_section(self, sec_heading='show', sec_name=None):
```

Please change this to 
```
return json.dumps({'text': self.get_show_section('logging buffered')}
```
and the rest should work OK

2020-10-22 23:26 UTC, claesmk commented on asa_parser/src/asa_parse.py
> +        return json.dumps({'text': self.get_show_section('show logging buffered')})
@LondonWesley any questions about the requested changes?

2020-10-23 01:30 UTC, claesmk commented
I think you checked-in the hidden .vs directory by mistake - please remove these files

2020-10-23 02:17 UTC, LondonWesley commented
Ok that should fix all the issues. Let me know if anything else arises.

2020-10-23 13:13 UTC, claesmk approved these changes

2020-10-23 13:13 UTC, merged